#encoding: utf-8

USERNAME = 'zs_alec'
PASSWORD = '19740512'
HOST = 'localhost'
PORT = 3306
DATABASE = 'spring'

SQLALCHEMY_DATABASE_URI = 'mysql://%s:%s@%s:%d/%s' % (USERNAME, PASSWORD, HOST, PORT, DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = False
