"""empty message

Revision ID: c2088518d4d2
Revises: 
Create Date: 2020-10-22 16:25:12.551513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2088518d4d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('py_demo1_prj_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False, comment='手机号码'),
    sa.Column('username', sa.String(length=10), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=100), nullable=True, comment='密码'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户数据表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('py_demo1_prj_user')
    # ### end Alembic commands ###
