"""empty message

Revision ID: e28f65d488be
Revises: 9f1567039fbc
Create Date: 2020-10-22 16:44:31.388952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e28f65d488be'
down_revision = '9f1567039fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('py_demo1_prj_user', 'username',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='用户名')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('py_demo1_prj_user', 'username',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='用户名')
    # ### end Alembic commands ###
