"""empty message

Revision ID: 6789b167995b
Revises: 
Create Date: 2020-10-20 17:42:40.286176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6789b167995b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('py_demo1_article2', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('py_demo1_article2', 'content')
    # ### end Alembic commands ###
