"""empty message

Revision ID: f206c30bf4b7
Revises: 6789b167995b
Create Date: 2020-10-20 17:54:12.769154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f206c30bf4b7'
down_revision = '6789b167995b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('py_demo1_article2', sa.Column('tag', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('py_demo1_article2', 'tag')
    # ### end Alembic commands ###
